# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acted_in',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='acted_in',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='acted_in',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
