# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170314_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='acted_in',
            name='actor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Actor'),
        ),
        migrations.AddField(
            model_name='acted_in',
            name='movie_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
